openapi: 3.0.3
info:
  title: Node.js Authentication Microservice
  summary: An authentication microservice powered by Express
  contact:
    name: Razvan Ludosanu
    url: https://learnbackend.dev
    email: razvan@learnbackend.dev
  license:
    name: MIT
  version: 1.0.0
paths:
  /health:
    get:
      description: A health check route for external monitoring
      responses:
        '200':
          description: Responds with information about the process
          content:
            'application/json':
              schema:
                type: object
                properties:
                  uptime:
                    description: The number of seconds elapsed since the process started
                    type: number
                  timestamp:
                    description: The number of milliseconds elapsed since Epoch
                    type: number
  /auth/login:
    post:
      description: A route for authentication
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                email:
                  description: A valid email address
                  type: string
                password:
                  description: A password
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User successfully logged in
          content:
            'application/json':
              schema:
                type: object
                properties:
                  token:
                    description: A JSON web token containing the user's ID
                    type: string
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                type: object
                properties:
                  message:
                    description: Invalid email address or password format
                    type: string
        '401':
          description: Unauthorized
          content:
            'application/json':
              schema:
                type: object
                properties:
                  message:
                    description: Password doesn't match hash
                    type: string
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                type: object
                properties:
                  message:
                    description: Email address not found
                    type: string
  /auth/signup:
    post:
      description: A route for account creation
      requestBody:
        content:
          'application/x-www-form-urlencoded':
            schema:
              type: object
              properties:
                email:
                  description: A valid email address
                  type: string
                password:
                  description: A password
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User successfully logged in
          content:
            'application/json':
              schema:
                type: object
                properties:
                  token:
                    description: A JSON web token containing the user's ID
                    type: string
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                type: object
                properties:
                  message:
                    description: Invalid email address or password format
                    type: string
        '409':
          description: Conflict
          content:
            'application/json':
              schema:
                type: object
                properties:
                  message:
                    description: Email address already exists
                    type: string
